In [1]:
#mean median mode SD Variance Quantile IQR

In [2]:
import pandas as pd
import numpy as np

# MEAN MEDIAN MODE SD

In [ ]:
# generating 1000 random no between 0 & 100
# every time we run this code it will generate new set of random numbers

In [60]:
dataset=np.random.randint(0,100,1000)

In [61]:
dataset

array([26, 19, 95, 10, 98, 90, 82, 36, 45, 99, 20, 14, 57, 97, 51, 62, 17,
       35,  6, 18, 52, 28, 59,  5, 41, 40, 66, 61, 60, 33, 81, 71, 57, 27,
       78, 85,  1, 61, 48, 88, 94,  0, 41, 46, 37, 89, 60, 51, 87, 79, 80,
       30,  1, 51, 54, 76, 40, 80, 92, 38, 72, 13, 38, 28, 71, 17, 64, 65,
       26, 28, 45, 58, 36, 49, 35, 77, 37, 58, 35, 30, 27, 13, 26,  3, 70,
       10,  8, 55, 57, 25,  1, 98, 38, 23, 35, 43, 64, 34, 62, 60, 11,  9,
        9,  2, 11, 26, 65, 14, 30, 52,  9, 34, 93, 70, 89, 86,  9, 43,  5,
       74, 51, 51, 12, 86, 57,  5, 51, 87, 22, 32, 47, 74, 75, 58, 95, 55,
       20, 11, 19, 17, 57, 50, 99,  9,  5, 24,  3, 28, 91, 61,  3, 49, 60,
       29, 78, 28, 10, 94, 47, 39,  5, 60, 71, 64, 23,  8,  7, 42, 46, 79,
       42, 37, 97, 29, 60, 96, 90, 50, 79, 51, 30, 51, 51, 94, 13, 33, 18,
       83, 96, 83, 25, 84, 81, 87, 61, 32, 56, 20, 43, 53, 14,  7, 48, 82,
       63, 11, 28, 26, 59, 34,  4, 69, 16, 17, 34,  6, 46, 57, 26, 64,  3,
       75, 64, 77, 24, 53

In [62]:
type(dataset)

numpy.ndarray

In [ ]:
#Creating sample size

In [74]:
dataset_1=np.random.choice(dataset,50)

In [75]:
dataset_1

array([55, 64, 31,  5, 52, 82,  8, 39, 41,  5, 74, 21, 82, 64, 70, 97, 53,
       78, 93,  6, 50,  6, 18, 26,  1, 49, 26, 78, 38, 37, 75, 16, 44, 55,
       18, 54, 79, 18, 97, 75, 19, 59, 71, 96, 64, 78, 51, 98, 59, 64])

In [76]:
dataset_2=np.random.choice(dataset,100)

In [77]:
dataset_2

array([21, 89, 22,  3, 29, 48, 98, 76, 80, 14, 53, 39, 23, 35, 50, 22,  7,
       52, 70, 43, 29, 97, 19, 38, 27, 14, 27, 75, 23,  1, 11, 76, 82, 84,
       46, 90, 54, 97,  2, 32, 68, 55, 79, 47, 11, 64, 17,  2, 78, 60, 61,
       75, 57, 57, 11, 22, 73, 79, 39, 51,  0, 60, 60, 60,  6, 11,  1, 99,
       74, 10, 24, 21, 61,  4, 60, 62, 71, 28, 24, 85, 42, 58, 19, 69, 64,
       34, 76, 95, 40, 77, 98, 60, 55, 74,  2, 13, 45, 50, 50, 72])

# mean

In [78]:
mean_1=np.mean(dataset_1)
print("mean of sample_size_1:  ",mean_1)

mean of sample_size_1:   50.78


In [79]:
print(np.mean(dataset_2))

47.18


# median

In [80]:
print(np.median(dataset_1))

53.5


In [81]:
print(np.median(dataset_2))

50.0


In [15]:
# mode can not be calculated in numpy

# mode

In [16]:
from scipy.stats import mode

In [82]:
print(mode(dataset))

ModeResult(mode=array([51]), count=array([19]))


In [83]:
print(mode(dataset_1))

ModeResult(mode=array([64]), count=array([4]))


# variance

In [84]:
 print(np.var (dataset))

811.8429990000001


In [85]:
 print(np.var (dataset_1))

795.4515999999999


# Calculating Sample Variance in Python




In [22]:
from statistics import variance 

#define data
data = [4, 8, 12, 15, 9, 6, 14, 18, 12, 9, 16, 17, 17, 20, 14]

#calculate sample variance
variance(data)

22.066666666666666

In [23]:
#calculating Population Variance in Python


In [86]:
from statistics import pvariance 

#define data
data = [4, 8, 12, 15, 9, 6, 14, 18, 12, 9, 16, 17, 17, 20, 14]

#calculate sample variance
pvariance(data)

20.595555555555556

In [25]:
print(np.var (data))

20.595555555555556


In [26]:
#numpy gives the population variance

In [87]:
from statistics import stdev

In [28]:
# sample standard deviation

In [88]:
stdev(data)

4.697517074654084

In [30]:
# population standard deviation

In [89]:
from statistics import pstdev

In [90]:
pstdev(data)

4.5382326466980025

# standard deviation

In [92]:
print(np.std(dataset))

28.49285873688353


In [93]:
 print(np.std(dataset_1))

28.2037515235119


# range

In [94]:
max(dataset)

99

In [95]:
min(dataset)

0

In [96]:
range=max(dataset)-min(dataset)

In [97]:
print(range)

99


# IQR

In [39]:
num_arr=np.random.randint(0,25,500)

In [40]:
num_arr

array([ 7, 10, 12,  3, 22,  2, 14, 12, 20, 12,  3,  4,  2, 21,  9, 18, 17,
        1,  9, 10, 15, 10,  1, 14,  8,  3, 17, 17, 23, 15, 23, 19, 19, 14,
        4, 22, 22, 21,  2,  8, 19, 12, 23,  1, 15, 11,  1, 20,  4,  3, 16,
        2, 10,  4, 23, 14,  2,  9,  7, 20,  5,  4, 18, 11,  3, 16,  1, 16,
       11, 10, 22, 10, 21, 21, 19, 14, 15, 11, 11, 15, 20,  2, 15, 20,  0,
       19, 17, 13, 24,  8, 14, 16,  5,  0, 23, 23,  0, 11, 20, 17, 24, 13,
       19, 19,  7, 23, 22,  7, 18, 23,  7, 18, 15, 15, 14, 14, 24,  1,  0,
       22, 20, 20,  3,  1, 18,  0, 24,  5,  9, 10, 21,  6,  5,  1, 22,  8,
       16,  6, 17, 13,  6, 16,  4, 20, 22, 21, 19,  0, 19,  9, 14, 21, 11,
        7,  1, 20,  9, 18, 13,  7,  7, 10, 22,  0,  4,  3, 24,  7,  6, 12,
        2,  3,  8, 22, 17, 22,  4, 21,  2, 13, 14,  9,  8, 12, 14, 22,  9,
        6,  8, 14,  5,  3, 21,  1,  5, 11,  3, 19,  2, 14,  7,  8,  6, 10,
        6, 22, 16, 16, 13, 13, 12, 11, 21, 22,  0, 21,  7, 12, 21, 23,  4,
       19, 23, 11, 17,  4

# IQR

In [41]:
# calculating 25 percentile
Q1=np.percentile(num_arr,25)
Q1

6.0

In [98]:
# when we added the value with 5 , percentile also added with 5
Q1=np.percentile(num_arr+5,25)
Q1

11.0

In [99]:
# when we increase value by 5% percentile also increase by 5%
Q1=np.percentile(1.05*(num_arr),25)
Q1

6.300000000000001

In [100]:
# when we increase value by 50 %,  percentile also increase by 50%
Q1=np.percentile(1.5*(num_arr),25)
Q1

9.0

In [42]:
# calculating 50 percentile
Q2=np.percentile(num_arr,50)
Q2

12.0

In [101]:
Q2=np.percentile(1.05*(num_arr),50)
Q2

12.600000000000001

In [43]:
# calculating 75 percentile
Q3=np.percentile(num_arr,75)
Q3

18.0

In [102]:

Q3=np.percentile(1.05*(num_arr),75)
Q3

18.900000000000002

In [44]:
# percentile and quantile work on sorted list

In [45]:
# percentile and quantile indicate the place in the list .

In [103]:
IQR=Q3-Q1

In [104]:
IQR

9.900000000000002

# loading and saving dataset from seaborn liabrary

In [48]:
#load_dataset()

In [49]:
#export a Pandas DataFrame to a CSV file. 
#to_csv() 

In [50]:
# Saving a downloaded dataset to csv file in our PC
import seaborn as sb
df11 = sb.load_dataset('tips')

df11.to_csv('tips_final.csv', index = True)